name_1_symbols = 'A'
name_40_symbols = 'Гордость и предубеждение гордость и пред'
name_41_symbols = 'Гордость и предубеждение гордость и преду'
book_1 = 'Мертвые души'
book_2 = 'Библия'
genre_in_list_1 = 'Фантастика'
genre_in_list_2 ='Детективы'
genre_not_in_list = 'Драма'